services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  ingestor:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:password@timescaledb:5432/postgres
    depends_on:
      - timescaledb
